ERROR.
	f=PosixPath('/home/lk3591/Documents/datasets/Sorel/processed/train/0029485484855b10fc4f2ea45e8582a2433230f2c81183913b9c40efb2a9b108')
	e=not_found('Could not parse: 0029485484855b10fc4f2ea45e8582a2433230f2c81183913b9c40efb2a9b108')
----------------------------------------------------------------------------------------
ERROR.
	f=PosixPath('/home/lk3591/Documents/datasets/Sorel/processed/train/0025d104bb389ddd438b453da230bd291ce1a7d6eaffc81102427de09f79dcca')
	e=not_found('Could not parse: 0025d104bb389ddd438b453da230bd291ce1a7d6eaffc81102427de09f79dcca')
----------------------------------------------------------------------------------------
ERROR.
	f=PosixPath('/home/lk3591/Documents/datasets/Sorel/processed/train/0026ce3f4c4132ed238c11c9b44a95ae0a84ea93a1abe200953d673b6dc98fa4')
	e=not_found('Could not parse: 0026ce3f4c4132ed238c11c9b44a95ae0a84ea93a1abe200953d673b6dc98fa4')
----------------------------------------------------------------------------------------

********************************************************************************

---------------------------------------- ERROR ----------------------------------------
f=/home/lk3591/Documents/datasets/Sorel/processed/train/002bbe40cd855b992d71cd91a1b9b1f2f2219b49b77341e1c1cf2ba0eb37fcde
attributions have nonzero chunk offset o=384
Traceback (most recent call last):
  File "modify_malware.py", line 427, in run_per_sample
    ) -> None:
ValueError: attributions have nonzero chunk offset o=384


locals:
{'attributions': tensor([-0.0050, -0.0050, -0.0050,  ...,  0.2341,  0.2341,  0.2341]),
 'attributions_path': PosixPath('outputs/gct/4000000/KernelShap/False/512/50/1/attributions'),
 'benign_attributions': tensor([0.0582, 0.0582, 0.0582,  ..., 0.5442, 0.5442, 0.5442]),
 'benign_iterable_callable': <__main__.TextSectionAttributionsIterable object at 0x7f05239af160>,
 'benign_replacement': tensor([205., 205., 205.,  ...,   1.,   1.,   1.]),
 'chunk_size': 512,
 'confidences_path': PosixPath('outputs/gct/4000000/KernelShap/False/512/50/1/confidences/pefile'),
 'e': ValueError('attributions have nonzero chunk offset o=384'),
 'f': PosixPath('/home/lk3591/Documents/datasets/Sorel/processed/train/002bbe40cd855b992d71cd91a1b9b1f2f2219b49b77341e1c1cf2ba0eb37fcde'),
 'l': 1152,
 'model': MalConvGCT(
  (pooling): AdaptiveMaxPool1d(output_size=1)
  (cat): CatMod()
  (embd): Embedding(257, 8, padding_idx=0)
  (context_net): MalConvML(
    (pooling): AdaptiveMaxPool1d(output_size=1)
    (cat): CatMod()
    (embd): Embedding(257, 8, padding_idx=0)
    (convs): ModuleList(
      (0): Conv1d(8, 512, kernel_size=(256,), stride=(64,))
    )
    (convs_1): ModuleList(
      (0): Conv1d(256, 256, kernel_size=(1,), stride=(1,))
    )
    (fc_1): Linear(in_features=256, out_features=256, bias=True)
    (fc_2): Linear(in_features=256, out_features=256, bias=True)
  )
  (convs): ModuleList(
    (0): Conv1d(8, 512, kernel_size=(256,), stride=(64,))
  )
  (linear_atn): ModuleList(
    (0): Linear(in_features=256, out_features=256, bias=True)
  )
  (convs_share): ModuleList(
    (0): Conv1d(256, 256, kernel_size=(1,), stride=(1,))
  )
  (fc_1): Linear(in_features=256, out_features=256, bias=True)
  (fc_2): Linear(in_features=256, out_features=2, bias=True)
),
 'o': 384,
 'run_flags': <Section: RUN_FLAGS>,
 'u': 11520}
---------------------------------------- ERROR ----------------------------------------

---------------------------------------- ERROR ----------------------------------------
index 0 is out of bounds for dimension 0 with size 0
Traceback (most recent call last):
File "modify_malware.py", line 447, in run_per_sample
if get_offset_chunk_tensor(attributions, chunk_size) != 0:
File "modify_malware.py", line 135, in get_offset_chunk_tensor
first = chunked_tensor[0]
IndexError: index 0 is out of bounds for dimension 0 with size 0

locals:
{'attributions': tensor([]),
'attributions_path': PosixPath('outputs/gct/4000000/KernelShap/False/512/50/1/attributions'),
'benign_attributions': tensor([0.0582, 0.0582, 0.0582,  ..., 0.5442, 0.5442, 0.5442]),
'benign_iterable_callable': <__main__.TextSectionAttributionsIterable object at 0x7f4284a07dc0>,
'benign_replacement': tensor([205., 205., 205.,  ...,   1.,   1.,   1.]),
'chunk_size': 512,
'confidences_path': PosixPath('outputs/gct/4000000/KernelShap/False/512/50/1/confidences/pefile'),
'e': IndexError('index 0 is out of bounds for dimension 0 with size 0'),
'f': PosixPath('/home/lk3591/Documents/datasets/Sorel/processed/test/00004eccc54e8ad87b9c20357f5ff9d0e351cfb94d90fed6028cb4c5f1e63b4e'),
'k.dtype': torch.float32,
'k.shape': torch.Size([0]),
'l': 4841472,
'len(k)': 0,
'model': MalConvGCT(
(pooling): AdaptiveMaxPool1d(output_size=1)
(cat): CatMod()
(embd): Embedding(257, 8, padding_idx=0)
(context_net): MalConvML(
(pooling): AdaptiveMaxPool1d(output_size=1)
(cat): CatMod()
(embd): Embedding(257, 8, padding_idx=0)
(convs): ModuleList(
(0): Conv1d(8, 512, kernel_size=(256,), stride=(64,))
)
(convs_1): ModuleList(
(0): Conv1d(256, 256, kernel_size=(1,), stride=(1,))
)
(fc_1): Linear(in_features=256, out_features=256, bias=True)
(fc_2): Linear(in_features=256, out_features=256, bias=True)
)
(convs): ModuleList(
(0): Conv1d(8, 512, kernel_size=(256,), stride=(64,))
)
(linear_atn): ModuleList(
(0): Linear(in_features=256, out_features=256, bias=True)
)
(convs_share): ModuleList(
(0): Conv1d(256, 256, kernel_size=(1,), stride=(1,))
)
(fc_1): Linear(in_features=256, out_features=256, bias=True)
(fc_2): Linear(in_features=256, out_features=2, bias=True)
),
'run_flags': <Section: RUN_FLAGS>,
'u': 4887040}
---------------------------------------- ERROR ----------------------------------------


---------------------------------------- ERROR ----------------------------------------
index 0 is out of bounds for dimension 0 with size 0
Traceback (most recent call last):
  File "/home/lk3591/Documents/MalConv2/modify_malware.py", line 447, in run_per_sample
    if get_offset_chunk_tensor(attributions, chunk_size) != 0:
  File "/home/lk3591/Documents/MalConv2/modify_malware.py", line 135, in get_offset_chunk_tensor
    first = chunked_tensor[0]
IndexError: index 0 is out of bounds for dimension 0 with size 0

locals:
{'attributions': tensor([]),
 'attributions_path': PosixPath('outputs/gct/4000000/KernelShap/False/512/50/1/attributions'),
 'benign_attributions': tensor([0.0582, 0.0582, 0.0582,  ..., 0.5442, 0.5442, 0.5442]),
 'benign_iterable_callable': <__main__.TextSectionAttributionsIterable object at 0x7f411471ec10>,
 'benign_replacement': tensor([205., 205., 205.,  ...,   1.,   1.,   1.]),
 'chunk_size': 512,
 'confidences_path': PosixPath('outputs/gct/4000000/KernelShap/False/512/50/1/confidences/pefile'),
 'e': IndexError('index 0 is out of bounds for dimension 0 with size 0'),
 'f': PosixPath('/home/lk3591/Documents/datasets/Sorel/processed/test/00004eccc54e8ad87b9c20357f5ff9d0e351cfb94d90fed6028cb4c5f1e63b4e'),
 'k.dtype': torch.float32,
 'k.shape': torch.Size([0]),
 'l': 4841472,
 'len(k)': 0,
 'model': MalConvGCT(
  (pooling): AdaptiveMaxPool1d(output_size=1)
  (cat): CatMod()
  (embd): Embedding(257, 8, padding_idx=0)
  (context_net): MalConvML(
    (pooling): AdaptiveMaxPool1d(output_size=1)
    (cat): CatMod()
    (embd): Embedding(257, 8, padding_idx=0)
    (convs): ModuleList(
      (0): Conv1d(8, 512, kernel_size=(256,), stride=(64,))
    )
    (convs_1): ModuleList(
      (0): Conv1d(256, 256, kernel_size=(1,), stride=(1,))
    )
    (fc_1): Linear(in_features=256, out_features=256, bias=True)
    (fc_2): Linear(in_features=256, out_features=256, bias=True)
  )
  (convs): ModuleList(
    (0): Conv1d(8, 512, kernel_size=(256,), stride=(64,))
  )
  (linear_atn): ModuleList(
    (0): Linear(in_features=256, out_features=256, bias=True)
  )
  (convs_share): ModuleList(
    (0): Conv1d(256, 256, kernel_size=(1,), stride=(1,))
  )
  (fc_1): Linear(in_features=256, out_features=256, bias=True)
  (fc_2): Linear(in_features=256, out_features=2, bias=True)
),
 'run_flags': <Section: RUN_FLAGS>,
 'u': 4887040}
---------------------------------------- ERROR ----------------------------------------
